"""create drone_telemetry and pipeline_run tables

Revision ID: 4fb3a7ad895f
Revises: 
Create Date: 2026-08-23 12:29:45.103020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb3a7ad895f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.String(length=64), nullable=False),
    sa.Column('drone_type', sa.String(length=50), nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('battery_percent', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'landed', 'lost_signal', name='drone_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drone_id', 'timestamp', name='uq_drone_telemetry_drone_id_timestamp')
    )
    op.create_index(op.f('ix_drone_telemetry_drone_type'), 'drone_telemetry', ['drone_type'], unique=False)
    op.create_index(op.f('ix_drone_telemetry_operator_id'), 'drone_telemetry', ['operator_id'], unique=False)
    op.create_index(op.f('ix_drone_telemetry_status'), 'drone_telemetry', ['status'], unique=False)
    op.create_index(op.f('ix_drone_telemetry_timestamp'), 'drone_telemetry', ['timestamp'], unique=False)
    op.create_table('pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('started', 'completed', 'failed', name='pipeline_run_status', native_enum=False, create_constraint=True, length=20), server_default='started', nullable=False),
    sa.Column('total_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('invalid_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_run')
    op.drop_index(op.f('ix_drone_telemetry_timestamp'), table_name='drone_telemetry')
    op.drop_index(op.f('ix_drone_telemetry_status'), table_name='drone_telemetry')
    op.drop_index(op.f('ix_drone_telemetry_operator_id'), table_name='drone_telemetry')
    op.drop_index(op.f('ix_drone_telemetry_drone_type'), table_name='drone_telemetry')
    op.drop_table('drone_telemetry')
    # ### end Alembic commands ###
